//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class consultas
    {
        public int id { get; set; }
        public string producto { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> idSucursalProducto { get; set; }
        public Nullable<int> idSucursal { get; set; }
        public string sucursal { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public string direccion { get; set; }
        public Nullable<decimal> distancia { get; set; }
        public Nullable<int> idFarmacia { get; set; }
    }
}
