//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESCUENTO
    {
        public int ID_DESCUENTO { get; set; }
        public int ID_SUCURSAL_PRODUCTO { get; set; }
        public System.DateTime FECHA_DESDE { get; set; }
        public System.DateTime FECHA_HASTA { get; set; }
        public decimal DESCUENTO1 { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual SUCURSAL_PRODUCTO SUCURSAL_PRODUCTO { get; set; }
    }
}
