//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCIDENCIA
    {
        public int ID_INCIDENCIA { get; set; }
        public int ID_PEDIDO { get; set; }
        public string INCIDENCIA1 { get; set; }
        public System.DateTime FECHA_INCIDENCIA { get; set; }
        public System.DateTime FECHA_RESUELTO { get; set; }
        public string OBSERVACION { get; set; }
        public string ESTADO { get; set; }
    
        public virtual PEDIDO PEDIDO { get; set; }
    }
}
