//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUCURSAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUCURSAL()
        {
            this.EMPLEADO_SUCURSAL = new HashSet<EMPLEADO_SUCURSAL>();
            this.PEDIDO = new HashSet<PEDIDO>();
        }
    
        public int ID_SUCURSAL { get; set; }
        public int ID_FARMACIA { get; set; }
        public string SUCURSAL1 { get; set; }
        public string DIRECCION { get; set; }
        public string LONGITUD { get; set; }
        public string LATITUD { get; set; }
        public string TELEFONO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADO_SUCURSAL> EMPLEADO_SUCURSAL { get; set; }
        public virtual FARMACIA FARMACIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
    }
}
