//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUCURSAL_PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUCURSAL_PRODUCTO()
        {
            this.DESCUENTO = new HashSet<DESCUENTO>();
        }
    
        public int ID_SUCURSAL_PRODUCTO { get; set; }
        public int ID_SUCURSAL { get; set; }
        public int ID_PRODUCTO { get; set; }
        public System.DateTime FECHA_VENCIMIENTO { get; set; }
        public int EXISTENCIA { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DESCUENTO> DESCUENTO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual SUCURSAL SUCURSAL { get; set; }
    }
}
