//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OAUTHTOKEN
    {
        public int AUTHTOKEN_ID { get; set; }
        public string SENDER_ID { get; set; }
        public string OUTH_NAME { get; set; }
        public string TOKEN { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    }
}
