//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACCION_PAGO
    {
        public int ID_TRANSACCION_PAGO { get; set; }
        public int ID_DETALLE_FACTURA { get; set; }
        public int ID_TIPO_PAGO { get; set; }
        public System.DateTime FECHA_TRANSACCION { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual DETALLE_FACTURA DETALLE_FACTURA { get; set; }
        public virtual TIPO_PAGO TIPO_PAGO { get; set; }
    }
}
